name: we_trade

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  algolia: ^1.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  back_button_interceptor: ^5.0.0
  bot_toast: ^4.0.1
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^2.1.0
  collection: ^1.15.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  date_format: ^2.0.2
  dots_indicator: ^2.0.0
  eva_icons_flutter: ^3.0.0
  expand_widget: ^2.0.0
  extended_sliver: ^2.0.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  firebase_database: ^7.0.0
  flash: ^2.0.0
  flutter_card_swipper: ^0.4.0
  flutter_form_builder: ^6.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.4
  group_button: ^2.1.0
  http: ^0.13.2
  implicitly_animated_reorderable_list: ^0.4.0
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.1
  line_icons: ^2.0.1
  loading_overlay: ^0.3.0
  lottie: ^1.0.1
  material_floating_search_bar: ^0.3.4
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.0.0
  provider: ^5.0.0
  search_choices: ^2.0.3
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  toggle_switch: ^1.1.0
  image_picker: ^0.8.0+3
  dropdown_formfield: ^0.1.3
  firebase_storage: ^8.1.0
  permission_handler: ^8.0.0+2
  multi_image_picker2: ^5.0.0
  path_provider: ^2.0.2
  cached_network_image: ^3.0.0
  pinch_zoom: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logos/logo.png'

flutter:
  uses-material-design: true

  assets:
    - lang/
    - assets/
    - assets/icons/
    - assets/icons/auth/
    - assets/images/
    - assets/images/logos/
    - assets/images/products_images_temp/
    - assets/images/on_boarding_screen/
    - assets/images/secondary_splash_screen/
    - assets/images/message/
